[clickhouse]
user = 'default'
passsword = ''

[backup]
target = 'File'
dir = '/var/backups/clickhouse'

# 1 full backup per week by default / on every 7th run
# 0 = full backup on every run.
incremental_backups = 6
# keep 2 full backups by default + their incrementals
retention = 2